### ISSUE TITLE
Compilation fails on clean install of CentOS 6.4 and Ubuntu 13.04

### ISSUE THREAD

**Issue by dgrine** [schedulix/schedulix#1]
Being keen to try out Schedulix, I've spent the last three days trying to get it to compile using the Installation guide (installation_en.pdf) included in the tree.

My system:
- Clean install of CentOS 6.4 - 64-bit
- Clean install of Ubuntu 13.04 - 64-bit
  - all software components as required by the documentation.

On both systems, compilation failure starts with a lot of complaints from Java about missing packages and it being unable to resolve all the symbols: 'cannot find symbol'. Again, I've followed the instructions and CLASSPATH is correctly set. After all these error messages, the make process finishes with:
/bin/sh: /home/<user>/schedulix/tools/bin/jay.linux: /lib/ld-linux.so.2: BAD ELF interpreter: no such file or directory

So 2 issues here:
- the java compilation fails
- 32 bit libraries are required (although the documentation doesn't seem to mention this, unless I'm mistaken)

After getting the 32-bit version by installing glibc.i686, I still get the Java messages (as expected) but now stumble upon the following:

Error: scanner can't have int and reference return type at the same type.

I've been trying to get around these issues by checking the class path and checking package versions etc., but I cannot get it to compile. I would much appreciate any help that would enable me to resolve this issue.

Thanks!

**Comment by SilviaMo** [comment]
Hi, I just followed the steps and I got the error ERROR: Could find neither jflex.Main nor JFlex.Main ERROR: Did you set your CLASSPATH correctly ?
I'm doing it in Centos 7. Is it possible I'm doing something wrong?

**Comment by schedulix** [comment]
Hi SilviaMo,

did you install jflex?

"yum install jflex"

(as root) should do it.

If you have, could you make a small change to $SDMSHOME/tools/bin/jflex and add a "-x" flag to the hashbang, try again and send me the output?


Thank you,

Ronald


-- 
independIT Integrative Technologies GmbH
Bergstrasse 6
86529 Schrobenhausen
Germany
HRB Ingolstadt 101.521
Geschäftsührer:
  Dieter Stubler, Dipl. Inform. (FH)
  Ronald Jeninga, Diplom Mathematiker 

e-mail: ronald.jeninga@independit.de
web: http://www.independit.de
Tel: +49 9129 2969040
GSM: +49 1520 1849816
Fax: +49 8252 9658034

**Comment by SilviaMo** [comment]
Hi Ronald, thanks for the quick response!!! I really appreciate it. 
I installed jflex and i have the 1.4.3 version. 
Sorry i didn't get your comment, you mean to change the variable $SDMSHOME or the CLASSPATH variable? where I have to add the "-x" flag? I'm really new on unix environment. :(

**Comment by SilviaMo** [comment]
Hi Ronald, 

  I have set the CLASSPATH as $SDMSHOME/tools/bin/jflex and tried again the make, I hope I did it fine. I got the below output.

find: ‘de’: No such file or directory
find: ‘de’: No such file or directory
cd /home/schedulix/schedulix/src; \
mkdir -p de/independit/scheduler; \
for fff in *; do \
        if [ "${fff}" != "de" -a ! -e de/independit/scheduler/${fff} ]; then \
                ln -s /home/schedulix/schedulix/src/${fff} de/independit/scheduler/${fff}; \
        fi; \
done
make[1]: Entering directory `/home/schedulix/schedulix/src/server'
make[2]: Entering directory `/home/schedulix/schedulix/src/server/parser'
make[3]: Entering directory `/home/schedulix/schedulix/src/server/parser/cmdline'
/home/schedulix/schedulix/tools/bin/jay -v CmdLineParser.jay /home/schedulix/schedulix/tools/lib/skeleton > CmdLineParser.java
egrep -e "^//yy" < CmdLineParser.java | sed 's!//yy!!' > parser.tables
/home/schedulix/schedulix/tools/bin/jflex -d /tmp CmdLineScanner.jlex
***************************************************
ERROR: Could find neither jflex.Main nor JFlex.Main
ERROR: Did you set your CLASSPATH correctly ?
***************************************************
make[3]: *** [CmdLineScanner.java] Error 1
make[3]: Leaving directory `/home/schedulix/schedulix/src/server/parser/cmdline'
make[2]: *** [commongensubdirs] Error 2
make[2]: Leaving directory `/home/schedulix/schedulix/src/server/parser'
make[1]: *** [commongensubdirs] Error 2
make[1]: Leaving directory `/home/schedulix/schedulix/src/server'
make: *** [commongensubdirs] Error 2

**Comment by schedulix** [comment]
Hi SilviaMo,

if you just enter "jflex --version" from the shell, what happens?
Here I get
```
[ronald@ocelot src]$ jflex --version
This is JFlex 1.4.3

```
And what I meant with changing the hashbang is:
Open $SDMSHOME/tools/bin/jflex in an editor.
Change the first line from 

#!/bin/bash

to

#!/bin/bash -x

(#!interpreter is called hashbang or shebang)

Thank you,

Ronald

**Comment by SilviaMo** [comment]
Hi Ronald, 

Here I get:
   [schedulix@ip-172-31-20-138 src]$ jflex --version
   This is JFlex 1.4.3

Done I have added "-x" and tried again the make and I got:

[schedulix@ip-172-31-20-138 src]$ make
cd /home/schedulix/schedulix/src; \
mkdir -p de/independit/scheduler; \
for fff in *; do \
        if [ "${fff}" != "de" -a ! -e de/independit/scheduler/${fff} ]; then \
                ln -s /home/schedulix/schedulix/src/${fff} de/independit/scheduler/${fff}; \
        fi; \
done
make[1]: Entering directory `/home/schedulix/schedulix/src/server'
make[2]: Entering directory `/home/schedulix/schedulix/src/server/parser'
make[3]: Entering directory `/home/schedulix/schedulix/src/server/parser/cmdline'
/home/schedulix/schedulix/tools/bin/jflex -d /tmp CmdLineScanner.jlex
+ '[' -f /usr/share/java/java_cup-runtime.jar ']'
+ CUP=/usr/share/java/java_cup-runtime.jar
+ echo ://home/schedulix/schedulix/tools/bin/jflex/jflex.jar
+ grep -i jflex
+ for MAIN in jflex.Main JFlex.Main
+ java jflex.Main -version
+ grep -i 'this is'
+ for MAIN in jflex.Main JFlex.Main
+ java JFlex.Main -version
+ grep -i 'this is'
+ echo '***************************************************'
***************************************************
+ echo 'ERROR: Could find neither jflex.Main nor JFlex.Main'
ERROR: Could find neither jflex.Main nor JFlex.Main
+ echo 'ERROR: Did you set your CLASSPATH correctly ?'
ERROR: Did you set your CLASSPATH correctly ?
+ echo '***************************************************'
***************************************************
+ exit 1
make[3]: *** [CmdLineScanner.java] Error 1
make[3]: Leaving directory `/home/schedulix/schedulix/src/server/parser/cmdline'
make[2]: *** [commongensubdirs] Error 2
make[2]: Leaving directory `/home/schedulix/schedulix/src/server/parser'
make[1]: *** [commongensubdirs] Error 2
make[1]: Leaving directory `/home/schedulix/schedulix/src/server'
make: *** [commongensubdirs] Error 2

**Comment by schedulix** [comment]
Hi SilviaMo,

well, we'll have to try to find the correct jar file then.
Usually the jar file is located somewhere below /usr/share/java
On my CentOS7 it is called JFlex.jar or jflex.jar.
Those names should be found automatically. Hence the jar file will be called differently, I assume.

Could you give it a try to find the jflex jar file?
They might have called it differently or have placed it at some different location (probably the first option).

Sorry for the hassle.

Regards,

Ronald

**Comment by SilviaMo** [comment]
Hi Ronald,

The jflex.jar file is located in the location you suggested.

[schedulix@ip-172-31-27-174 schedulix]$ ls /usr/share/java
java_cup.jar  java_cup-runtime.jar  jflex.jar  JFlex.jar
[schedulix@ip-172-31-27-174 schedulix]$

There is no a hassle form you on the contrary! I appreciate your help!
Regards, 
Silvia Monroy

**Comment by schedulix** [comment]
Hi Silvia,

for some reason the output of your jflex script with the "-x" set differs from what I get here.
Just to make sure we're talking about the same schedulix release, which one do you try to compile?

my output looks like

```
/home/ronald/schedulix-2.8/tools/bin/jflex MiniParse.jlex
+ '[' -f /usr/share/java/java_cup-runtime.jar ']'
+ CUP=/usr/share/java/java_cup-runtime.jar
+ echo :.
+ grep -i jflex
+ echo 'WARNING: Didn'\''t find jflex.jar or similar in CLASSPATH'
WARNING: Didn't find jflex.jar or similar in CLASSPATH
+ '[' -d /usr/share/java ']'
++ head -1
++ ls /usr/share/java/jflex.jar /usr/share/java/JFlex.jar
+ X=/usr/share/java/jflex.jar:/usr/share/java/java_cup-runtime.jar
+ '[' 0 -eq 0 ']'
+ export CLASSPATH=/usr/share/java/jflex.jar:/usr/share/java/java_cup-runtime.jar::.
+ CLASSPATH=/usr/share/java/jflex.jar:/usr/share/java/java_cup-runtime.jar::.
+ for MAIN in jflex.Main JFlex.Main
+ java jflex.Main -version
+ grep -i 'this is'
+ for MAIN in jflex.Main JFlex.Main
+ java JFlex.Main -version
+ grep -i 'this is'
+ java JFlex.Main MiniParse.jlex
Reading "MiniParse.jlex"

```
and as you can see, the script sets the CLASSPATH correctly.
I checked, it looks exactly  the same in 2.7.

Regards,

Ronald

**Comment by SilviaMo** [comment]
Hi Ronald, 

   I'm using the version 2.7 using the command git clone https://github.com/schedulix/schedulix.git -b v2.7
and following the next steps:
1.(root) yum update to get the newest system software
2.(root) yum install git
3.(root) yum groupinstall "Java Platform"
4.(root) yum install gcc gcc-c++
5.(root) yum install jflex
6.(root) yum install glibc.i686
7.(root) yum install make
8.(root) yum install java-1.6.0-openjdk-devel java-1.7.0-openjdk-devel
9.(root) yum install eclipse-swt
    cd /tmp
    wget ftp://ftp.icm.edu.pl/vol/rzm6/linux-slc/centos/7.1.1503/sclo/x86_64/rh/devtoolset-3/devtoolset-3-eclipse-swt-4.4.2-4.bootstrap2.el7.x86_64.rpm
    rpm -Uvh devtoolset-3-eclipse-swt-4.4.2-4.bootstrap2.el7.x86_64.rpm

1.(root) useradd schedulix -m -U -s /bin/bash
2.(root) su - schedulix
3.(schedulix) git clone https://github.com/schedulix/schedulix.git
4.(schedulix) added to .bashrc:
 export SDMSHOME=/home/schedulix/schedulix
 export CLASSPATH=$CLASSPATH:/usr/share/java/jflex.jar
 export JAVAHOME=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64
 export SWTJAR=/opt/rh/devtoolset-3/root/usr/lib64/eclipse/swt.jar
5.(schedulix) . .bashrc
6.(schedulix) cd schedulix/src
7.(schedulix) make

**Comment by schedulix** [comment]
Hi Silvia,

thank you! You're using Java 1.6, if I read that correctly, you need java 1.7.
That's probably the cause of the problem.

Regards,

Ronald

**Comment by SilviaMo** [comment]
So, should I set JAVAHOME variable as JAVAHOME=/usr/lib/jvm/jre-1.7.0-openjdk-1.7.0.141-2.6.10.1.el7_3.x86_64

because i have next in that path
[schedulix@ip-172-31-27-174 src]$ ls /usr/lib/jvm/
java                                                java-1.8.0                                       jre-1.7.0
java-1.6.0                                          java-1.8.0-openjdk                               jre-1.7.0-openjdk
java-1.6.0-openjdk-1.6.0.41.x86_64                  java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64  jre-1.7.0-openjdk-1.7.0.141-2.6.10.1.el7_3.x86_64
java-1.6.0-openjdk.x86_64                           java-openjdk                                     jre-1.8.0
java-1.7.0                                          jre                                              jre-1.8.0-openjdk
java-1.7.0-openjdk                                  jre-1.6.0                                        jre-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64
java-1.7.0-openjdk-1.7.0.141-2.6.10.1.el7_3.x86_64  jre-1.6.0-openjdk.x86_64                         jre-openjdk
[schedulix@ip-172-31-27-174 src]$

**Comment by schedulix** [comment]
Both 1.7 and 1.8 are ok, just not 1.6.
Please check what
`java -version`
reports. If it reports 1.6 then you'll have to set your default java to one of the other releases.
Generally I think that it is best to use a value for JAVA_HOME that fits the java you execute.

**Comment by SilviaMo** [comment]
I think I know what is the issue, I did the java --version and i got the next:

[schedulix@ip-172-31-27-174 src]$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

It seems there is no java executed in my server. I'll solve this and try again to compile and see if it works.

**Comment by schedulix** [comment]
Java is a bit different. Often programs know a "-v" and a "--version" command line option. The long option gets two dashes.
With Java the -version option gets a single dash only.

Regards,

Ronald

**Comment by SilviaMo** [comment]
OOhh yes you are right!... i did java -version and I got this:

[root@ip-172-31-20-138 ~]# java -version
java version "1.7.0_141"
OpenJDK Runtime Environment (rhel-2.6.10.1.el7_3-x86_64 u141-b02)
OpenJDK 64-Bit Server VM (build 24.141-b02, mixed mode)
[root@ip-172-31-20-138 ~]#

**Comment by schedulix** [comment]
Hi Silvia,

hm, this means we're back at our starting point then.
You are using Java 1.7, which is good.
The jflex jar file is where my script expects it to be.
You even set your CLASSPATH to point to the jflex.jar which explains the differences in output of the bash.

Ergo, the problem must occur in the 2nd part of the script, where I try to find out what the main class is called. That part looks like
```
for MAIN in jflex.Main JFlex.Main; do
        # since both "class not found" and "java $MAIN -version" return 1
        # we have to read the output. Fortunately JFlex tells us something
        # like "This is JFlex 1.4.3" or so
        if java $MAIN -version 2>/dev/null | grep -i "this is" >/dev/null 2>&1; then
                java $MAIN $@
                exit $?
        fi
done

```
If I do
```
[ronald@ocelot schedulix-2.7]$ jar tvf /usr/share/java/jflex.jar | grep -i main
  7976 Tue Jan 01 00:00:00 CET 1980 JFlex/Main.class
   634 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$1.class
   910 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$10.class
   871 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$11.class
   661 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$2.class
   662 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$3.class
   661 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$4.class
   661 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$5.class
   661 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$6.class
   661 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$7.class
   908 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$8.class
   869 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame$9.class
  6971 Tue Jan 01 00:00:00 CET 1980 JFlex/gui/MainFrame.class

```
it is visible what the Main class is called. (The MainFrame* classes are unimportant here).
What does it look like on your side?

If you want, we can communicate directly by e-mail and just post the result as soon as we've figured out what's happening. (ronald dot jeninga at independit dot de).
It would also stop you from posting your ip-address with a valid user name. (I edited your post to hide that invitation for hackers)

Regards,

Ronald

**Comment by schedulix** [comment]
The problem was caused by a flaw in the $SDMSHOME/tools/bin/jflex script.
If the CLASSPATH already contained the jflex.jar, the java_cup-runtime.jar wasn't added to the it.
JFlex crashed because the cup classes couldn't be found.

I fixed this and uploaded the fix to github. (both 2.7 and the unstable branch)
