### ISSUE TITLE
SDMS Command failed

### ISSUE THREAD

**Issue by Kevindroid** [schedulix/schedulix#11]
Hey guys!
      Last night I finished the installation of schedulix and everything seemed normal.This morning when I was reading the manual, the admin told me he deleted the mysql database remissly. Then I reinstall the mysql and start from page 17 of the installation pdf, user schedulix and database schedulixdb are set. I can also open the manage page. But when I open the SDMS and click any button, the page says ERRORMESSAGE ConnectError(ConnectError).  How can I repair this?
       Best regards!

**Comment by schedulix** [comment]
Hi Kevindroid,
did you start your server? The server will definitely crash if you drop the database while it's running (somehow logical, I think). And if the server isn't running, the Zope server will definitely have its difficulties connecting to a non existing process.

If the server is running, you might have a firewall problem. The server listens per default on port 2506(TCP).

We prefer to discuss issues like this in the schedulix google group.

Regards,

Ronald
