### ISSUE TITLE
Provide docker images and docker-compose config

### ISSUE THREAD

**Issue by nilp0inter** [schedulix/schedulix#12]
Hi!

Are there any plans of providing docker images + compose configuration? Are you open to pull requests?

Best regards,
Roberto

**Comment by schedulix** [comment]
Hi Roberto,

sorry for the late reply.
So far we didn't plan to provide docker packages. But if you feel like building some, and more importantly to build some scripts that automates the process, it'll be easy to add another target in the top level makefile. It would work just like building the rpms (make rpm).
I'm not a docker specialist, but AFAIK newly created files will be removed when shutting down a container.
In case of an agent it means that the task files would be removed and the agent would forget everything about the jobs currently running.
And if changes to files are reverted when a container is shut down, the Web GUI will "forget" about new bookmarks and users, resp. changed user preferences.

I am open to pull requests. But I am a bit picky in accepting changes, especially changes in the Java code. In case of a method to create docker containers you'll probably add a bunch of files. That's less critical and likely to be accepted.

Again, sorry for the late reply. I've been pretty busy with the new release (2.9). We'll officially release it this week.

Best regards,

Ronald
