### ISSUE TITLE
Missing files in examples

### ISSUE THREAD

**Issue by rafaelorafaelo** [schedulix/schedulix#13]
Hi, there are two or more files missing used in install/setup_examples.sdms - frosch.sh and dog.sh.
Regards
Ralf

**Comment by schedulix** [comment]
Hi Ralf,
thank you for pointing this out.
I'll add those files next week (I'm currently drowning in work, sorry).
They are usually stored in /opt/schedulix/schedulix/bin.
Regards,
Ronald

**Comment by schedulix** [comment]
Hi Ralf,
I've just added the files. I didn't test the examples though.
If you encounter problems, please advise.
Regards,
Ronald

**Comment by schedulix** [comment]
Sometimes the frog manages to escape. I've seen it happen :-)
Thank you for the feedback!
