### ISSUE TITLE
the schedulix-server-pg package relies on postgres being present on the same server

### ISSUE THREAD

**Issue by wouterhund** [schedulix/schedulix#15]
Hi,

We are using schedulix with postgresql, and would like to install schedulix from an rpm. The `schedulix-server-pg` package seems to be the way to go, since it contains the `server-start` scripts and various other data files.

Unfortunately it also includes [a preinstall script](https://github.com/schedulix/schedulix/blob/master/lib/server-pg_pre.script) which tries to initialize a postgresql server on the same system that schedulix is installed to, which for us, is not the case. We have a separate database server which is already configured.

I see two options:

* Provide a way to skip this initialization when installing `schedulix-server-pg` (using an environment variable perhaps?)

* Restructure the packages so we can still get the relevant `server-start` (etc) scripts without the postgresql dependency, we can provide our own config files.

The first would be far simpler as it works with the current package structure, and the script already looks at environment variables to adjust its behavior so this wouldn't be out of the ordinary.

We are currently working around this problem by skipping the pre-install script of schedulix-server-pg, however yum does not support this natively. So we're currently using the following invocation:

```
    curl https://www.schedulix.org/de/Downloads/schedulix-repo.rpm > /tmp/schedulix-repo.rpm \
 && yum install -y /tmp/schedulix-repo.rpm \
 && yum makecache \
 && yum install -y schedulix-base schedulix-client schedulix-zope \
 && yum install --downloadonly --downloaddir=/tmp schedulix-server-pg \
 # The following command will fail (hence the || true), since it tries to start a postgres daemon, which we don't have
 # But we do need yum to install the dependencies, so we let yum run, and fail, then use rpm --noscripts to finish the installation
 && yum install -y /tmp/schedulix-server-pg*.rpm || true \
 && rpm -U --noscripts /tmp/schedulix-server-pg*.rpm \
 && rm -rf /tmp/*.rpm
```

**Comment by schedulix** [comment]
schedulix cannot run without a repository database equipped with a proper schema.
And as you've found out yourself, schedulix can be configured to access a remote database system.
I could provide a third "server" rpm that leaves the initialisation of the database and the configuration (server.conf, DbURL and friends, java.conf JDBC driver jar) up to the user. I would call it `schedulix-server-rmt` or so, to indicate a remote database server. The resulting pre and post scripts would be pretty empty. Would that help?

**Comment by wouterhund** [comment]
That would be good.

We're fine managing the set up of the database server and its schema ourselves, and we're already managing the configuration files and the installation of the jdbc jar.

The only thing is that we'd still need to be able to get the `/opt/schedulix/schedulix/sql/` files somehow for when we want to run provision the database. Perhaps you could include the sql files for both postgres & mariadb in the `schedulix-server-rmt` package?

**Comment by schedulix** [comment]
Hi Wouter,

I'm making progress with the new schedulix-server-rmt rpm. Would it be possible to collaborate a little "offline"? I could send you the rpm by e-mail, and you test it. If it works I'll commit the changes and upload a new set of rpms to our server. If not, I'll do some repairs and we repeat the procedure.

But I'd need to know your e-mail address for it to work. Just drop me an e-mail if you're OK with this.
(ronald dot jeninga at independit dot de)

Best regards,

Ronald

**Comment by schedulix** [comment]
I've uploaded a new set of rpms (2.9-18), including schedulix-server-rmt.
Please tell me if it works for you.

**Comment by wouterhund** [comment]
Thanks a lot! I've just updated our installation scripts to use the new rmt package which simplified things a lot. Initial impressions are good, but we still have to go through testing.

**Comment by schedulix** [comment]
Hi Wouter,

thank you for the feedback! I'm happy it works for you.
I'll close this issue now. If your testing reveals new issues, don't hesitate to report them.

Best regards,

Ronald
