### ISSUE TITLE
 yum install fails to get required package " schedulix-base = 2.9-28.el7"

### ISSUE THREAD

**Issue by dmitrychebayewski** [schedulix/schedulix#21]
Hello. 
We are using deploying Schedulix into a Kubertenes cluster, and we would like to install Schedulix from rpm using Docker.
Unfortunately,  this morning we noticed a failure that we did not use to observe before.

--> Processing Dependency: schedulix-base = 2.9-28.el7 for package: schedulix-client-2.9-28.el7.x86_64
--> Running transaction check
---> Package hwdata.x86_64 0:0.252-9.7.el7 will be installed
---> Package schedulix-client.x86_64 0:2.9-28.el7 will be installed
--> Processing Dependency: schedulix-base = 2.9-28.el7 for package: schedulix-client-2.9-28.el7.x86_64
--> Finished Dependency Resolution
Error: Package: schedulix-client-2.9-28.el7.x86_64 (schedulix)
           Requires: schedulix-base = 2.9-28.el7
           Available: schedulix-base-2.8-25.el7.x86_64 (schedulix)
               schedulix-base = 2.8-25.el7
           Available: schedulix-base-2.9-22.el7.x86_64 (schedulix)
               schedulix-base = 2.9-22.el7
           Available: schedulix-base-2.9-23.el7.x86_64 (schedulix)
               schedulix-base = 2.9-23.el7
           Available: schedulix-base-2.9-24.el7.x86_64 (schedulix)
               schedulix-base = 2.9-24.el7
           Available: schedulix-base-2.9-25.el7.x86_64 (schedulix)
               schedulix-base = 2.9-25.el7
           Available: schedulix-base-2.9-26.el7.x86_64 (schedulix)
               schedulix-base = 2.9-26.el7
           Available: schedulix-base-2.9-27.el7.x86_64 (schedulix)
               schedulix-base = 2.9-27.el7
           Available: schedulix-base-2.9-28.el7.x86_64 (schedulix)
               schedulix-base = 2.9-28.el7
           Installing: schedulix-base-2.9-29.el7.x86_64 (schedulix)
               schedulix-base = 2.9-29.el7
           Available: schedulix-base-2.10-3.el7.x86_64 (schedulix)
               schedulix-base = 2.10-3.el7
           Available: schedulix-base-2.10-4.el7.x86_64 (schedulix)
               schedulix-base = 2.10-4.el7
           Available: schedulix-base-2.10-5.el7.x86_64 (schedulix)
               schedulix-base = 2.10-5.el7
           Available: schedulix-base-2.10-6.el7.x86_64 (schedulix)
               schedulix-base = 2.10-6.el7
           Available: schedulix-base-2.10-7.el7.x86_64 (schedulix)
               schedulix-base = 2.10-7.el7
           Available: schedulix-base-2.10-8.el7.x86_64 (schedulix)
               schedulix-base = 2.10-8.el7
           Available: schedulix-base-2.10-9.el7.x86_64 (schedulix)
               schedulix-base = 2.10-9.el7
           Available: schedulix-base-2.10-10.el7.x86_64 (schedulix)
               schedulix-base = 2.10-10.el7
           Available: schedulix-base-2.10-11.el7.x86_64 (schedulix)
               schedulix-base = 2.10-11.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
The command '/bin/sh -c yum install -y epel-release  && yum install -y       supervisor       gettext       wget       unzip       curl       ca-certificates       which  && curl https://www.schedulix.org/de/Downloads/schedulix-repo.rpm > /root/schedulix-repo.rpm  && yum install -y /root/schedulix-repo.rpm  && yum makecache  && yum install -y schedulix-base-$SCHEDULIX_VERSION schedulix-client-$SCHEDULIX_VERSION schedulix-zope-$SCHEDULIX_VERSION schedulix-server-rmt-$SCHEDULIX_VERSION  && rm -rf /root/*.rpm' returned a non-zero code: 1
script returned exit code 1

We are currntly working around this issue with '--skip-broken' option. 
However, we did not expect to see any dependencies broken.

Below is a fragment of Dockerfile that reproduces the issue:
FROM centos:7
ARG SCHEDULIX_VERSION=2.9
EXPOSE 2300
RUN yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
RUN yum install -y postgresql96
RUN yum install -y epel-release \
 && yum install -y \
      supervisor \
      gettext \
      wget \
      unzip \
      curl \
      ca-certificates \
      which \
 && curl https://www.schedulix.org/de/Downloads/schedulix-repo.rpm > /root/schedulix-repo.rpm \
 && yum install -y /root/schedulix-repo.rpm \
 && yum makecache \
 && yum install -y schedulix-base-$SCHEDULIX_VERSION schedulix-client-$SCHEDULIX_VERSION schedulix-zope-$SCHEDULIX_VERSION schedulix-server-rmt-$SCHEDULIX_VERSION \
 && rm -rf /root/*.rpm.

Regards
Dmitry

**Comment by schedulix** [comment]
I've uploaded the client-2.9-29 rpm. It should work as before now.
I'll close the issue, as soon as you've confirmed that it works.
Best regards,
Ronald

**Comment by dmitrychebayewski** [comment]
Hi Ronald.

Thank you for prompt reaction.
I confirm that it works as before now.

Regards
Dmitry
