### ISSUE TITLE
Issue with Schedulix Schedulix GPG key

### ISSUE THREAD

**Issue by dmitrychebayewski** [schedulix/schedulix#22]
Hi Ronald.

We install Schedulix from Dockerfile, and we have same issue with Schedulix GPG key as we had in the 8th of October 2021.
Could you have a look, please?

Regards
Dmitry
```
Retrieving key from https://www.independit.de/repo/rpm-gpg/RPM-GPG-KEY-schedulix
Importing GPG key 0x34126473:
 Userid     : "<removed>"
 Fingerprint: 320c b848 119b 5242 9cc4 1025 b220 a76a 3412 6473
 From       : https://www.independit.de/repo/rpm-gpg/RPM-GPG-KEY-schedulix


Public key for schedulix-base-2.9-31.el7.x86_64.rpm is not installed


 Failing package is: schedulix-base-2.9-31.el7.x86_64
 GPG Keys are configured as: https://www.independit.de/repo/rpm-gpg/RPM-GPG-KEY-schedulix

The command '/bin/sh -c yum install -y epel-release  && yum install -y       supervisor       gettext       wget       unzip       curl       ca-certificates       which  && curl https://www.schedulix.org/de/Downloads/schedulix-repo.rpm > /root/schedulix-repo.rpm  && yum install -y /root/schedulix-repo.rpm  && yum makecache  && yum install -y schedulix-base-$SCHEDULIX_VERSION schedulix-client-$SCHEDULIX_VERSION schedulix-zope-$SCHEDULIX_VERSION schedulix-server-rmt-$SCHEDULIX_VERSION  && rm -rf /root/*.rpm' returned a non-zero code: 1

```

**Comment by schedulix** [comment]
Hi Dmitry,

I'm terribly sorry about this. Somehow I must have used the old key to sign the latest rpms.
I'll fix it and recreate the rpms today. I'll notify you as soon as they are available again.
If you are in a real hurry, use the previous rpm (2.9-30) for the time being.

Best regards,

Ronald

**Comment by schedulix** [comment]
Hi Dmitry,

I've now recreated the rpms for schedulix 2.9 and 2.10, both for RHEL7 and RHEL8, and uploaded them to our server.
Could you please check if it now works for you?

Thank you,

Ronald

**Comment by dmitrychebayewski** [comment]
Hi Ronald! 

Thank you for your prompt feedback!
We have re-tested the installation, and, of course it works for us now as expected.

I am going to close this issue.
Regards
Dmitry
