### ISSUE TITLE
Make on Debian 8 fails, error in MiniScanner.java

### ISSUE THREAD

**Issue by kgoedecke** [schedulix/schedulix#7]
I get the following errors during make. There seems to be an issue with MiniScanner.class.

Any suggestions? I'm using OpenJDK 7 as recommended in your documentation. 

```
++ -o /home/schedulix/schedulix-2.6.1/bin/jobexecutor jobexecutor.o
make[1]: Leaving directory '/home/schedulix/schedulix-2.6.1/src/jobserver'
make[1]: Entering directory '/home/schedulix/schedulix-2.6.1/src/shell'
javac -cp /home/schedulix/schedulix-2.6.1/src:/usr/lib/java/swt.jar:/usr/share/java/jna.jar -O MiniParser.java 
Note: /home/schedulix/schedulix-2.6.1/src/de/independit/scheduler/SDMSApp/Options.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
javac -cp /home/schedulix/schedulix-2.6.1/src:/usr/lib/java/swt.jar:/usr/share/java/jna.jar -O MiniScanner.java 
MiniScanner.java:946: error: orphaned default
        default: 
        ^
MiniScanner.java:1183: error: 'else' without 'if'
          else {
          ^
2 errors
/home/schedulix/schedulix-2.6.1/src/Makefile.CommonRules:69: recipe for target 'MiniScanner.class' failed
make[1]: *** [MiniScanner.class] Error 1
make[1]: Leaving directory '/home/schedulix/schedulix-2.6.1/src/shell'
/home/schedulix/schedulix-2.6.1/src/Makefile.CommonRules:47: recipe for target 'commonsubdirs' failed
make: *** [commonsubdirs] Error 2
```

**Comment by kgoedecke** [comment]
I got it working by manually editing the MiniScanner.java. I still think this is a bug and that my solution is just a quick and dirty fix.

**Comment by schedulix** [comment]
Hi,

the way it sounds, you're working with one of the wrong jflex versions. The 1.4.x versions work. I'm not 100% sure of the 1.5 versions. In case of a 1.6.x versions, not this error would occur (afaik), but the scanner would hang (they might have fixed it - it's a well known bug - but it might or might not have found its way to the Debian 8 distribution. The 1.7 version would work, but requires another skeleton. I didn't check in a solution to this yet.

Hence my question: what version of jflex are you using?

I agree that any required manual action _during_ the build is a bug.

**Comment by schedulix** [comment]
OK, I'll have a look at jflex 1.6.1. Maybe some trivial changes are required to support it (i.e. the git version, not necessarily the distributed version).

I'll post the results.

**Comment by schedulix** [comment]
Well, obviously they distribute a changed skeleton.nested (required for sdmsh, since the normal skeleton can't handle "nested input" (change of input stream forth and back)). As far as I could derive from the release notes, my reported bugs seem to be fixed in this version. So now it's my turn to find a generic solution to this.

**Comment by schedulix** [comment]
I checked in a change into the master branch about 2 weeks ago. It seemed to work for me. Does it work for you?

**Comment by kgoedecke** [comment]
Haven't had time to look through it so far. I'll get back to you later this week.

Kevin 

+49 176 638 758 42
+1 (512) 900 9344

**Comment by schedulix** [comment]
Hi Kevin,

since I didn't hear from you since about 6 months, I regard this issue as solved.
If you encounter new problems please tell me.

Regards,

Ronald
